/** @category Component */
export const enum ComponentType {
    AnimatedSprite = "AnimatedSprite",
    AudioListener = "AudioListener",
    AudioSource = "AudioSource",
    Behaviour = "Behaviour",
    Camera = "Camera",
    Component = "Component",
    ParallaxBackground = "ParallaxBackground",
    ParticleSystem = "ParticleSystem",
    Renderable = "Renderable",
    TerrainRenderer = "TerrainRenderer",
    Text = "Text",
    Texture = "Texture",
    TilemapRenderer = "TilemapRenderer",
    Transform = "Transform",
    Video = "Video",

    Collider = "Collider",
    CircleCollider = "CircleCollider",
    PolygonCollider = "PolygonCollider",
    RectangleCollider = "RectangleCollider",
    TerrainCollider = "TerrainCollider",
    TilemapCollider = "TilemapCollider",
    Rigidbody = "Rigidbody",
}
